version: '3'
services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
    - MYSQL_DATABASE=wordpress
    volumes:
    - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
    - app-network
  wordpress:
    depends_on:
    - db
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
    - WORDPRESS_DB_HOST=db:3306
    - WORDPRESS_DB_USER=$MYSQL_USER
    - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
    - WORDPRESS_DB_NAME=wordpress
    - MYSQL_USER=$MYSQL_USER
    - MYSQL_USER=$MYSQL_PASSWORD 
    volumes:
    - wordpress:/var/www/html
    networks:
    - app-network
  webserver:
    depends_on:
    - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./var/log/nginx:/var/log/nginx #log файлы.
    - wordpress:/var/www/html
    - ./nginx-conf:/etc/nginx/conf.d
    - /etc/letsencrypt:/etc/letsencrypt
    networks:
    - app-network
  certbot:
    depends_on:
    - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt
    - wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email tsuprick@gmail.com --agree-tos --no-eff-email --force-renewal -d test11.netpeak.tech
volumes:
  certbot-etc:
  wordpress:
  dbdata:
networks:
  app-network:
    driver: bridge
